# Generated by Django 3.2.3 on 2022-05-21 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('upfile', models.FileField(blank=True, null=True, upload_to='oa/%Y/%m/%d/', verbose_name='附件')),
            ],
            options={
                'verbose_name': 'OA附件',
                'verbose_name_plural': 'OA附件',
            },
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('recipients', models.CharField(blank=True, max_length=200, null=True, verbose_name='接收人列表')),
                ('selid', models.CharField(blank=True, max_length=200, null=True, verbose_name='接收人id列表')),
                ('level', models.SmallIntegerField(blank=True, choices=[(1, '普通'), (2, '重要'), (3, '非常重要')], default=1, null=True, verbose_name='等级')),
                ('time_send', models.DateTimeField(verbose_name='发送时间')),
                ('time_new', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('time_edit', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('deleted', models.SmallIntegerField(default=0, verbose_name='已删除')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('upfiles', models.ManyToManyField(to='wxj.OAfiles')),
            ],
            options={
                'verbose_name': 'OA事项',
                'verbose_name_plural': 'OA事项',
                'db_table': 'wxj_oa',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('depart', models.CharField(blank=True, max_length=50, null=True, verbose_name='部门')),
                ('chejian', models.CharField(blank=True, max_length=50, null=True, verbose_name='车间')),
                ('gangwei', models.CharField(blank=True, max_length=50, null=True, verbose_name='岗位')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='F', max_length=10, verbose_name='性别')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='地址')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('mima', models.CharField(blank=True, max_length=50, null=True, verbose_name='标记')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('image', models.ImageField(default='image/user/default.png', upload_to='image/user/%Y')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
